### PR TITLE
build-time variables

### PR DESCRIPTION
**Pull request by denwwer**
## Feature
Finding way to set my `RAILS_ENV` variable to `Dockerfile` was not successful and after saw Issue #12 I decided add this useful functionality.
Usage is simple:
```
heroku container:push web --arg RAILS_ENV=staging,HTTPS=on
```

### CODE REVIEW

**Comment by cvx** [comment]
Is there anything that we can help with to get this PR merged?

**Comment by dmathieu** [comment]
Could you rebase your branch so the CI can run the tests?

**Comment by denwwer** [comment]
@dmathieu rebased

**Comment by dmathieu** [comment]
I've enabled fork PRs builds in circle. Closing and reopening to trigger a build.

**Review by dmathieu — APPROVED** [review]

**Review by ojacobson — APPROVED** [review]
This looks really solid to me. Docs are good, argument handling looks correct, and it looks like it addresses the intended need. Thanks, @denwwer!

**Pull request merged**
